title: Stream Blog
description: Hiroo!
theme: just-the-docs

url: https://arcipond.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template


  color_scheme: dark
