title: Stream Blog
description: Hiroo!
theme: just-the-docs

url: https://arcipond.github.io


color_scheme: dark


callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: green
  warning:
    title: Warning
    color: red